In [56]:
import pandas as pd

In [3]:
policekillings = pd.read_csv('data/police_killings.csv')

In [4]:
policekillings.columns = policekillings.columns.str.replace("'",'').str.replace(' ','_')
policekillings.columns = policekillings.columns.str.replace('Street_Address_of_Incident','Address').str.replace('Zipcode','Zip')
policekillings = policekillings[policekillings.columns.drop(list(policekillings.filter(regex='Unnamed')))]

In [5]:
policekillings = policekillings.rename(columns={'Geography_(via_Trulia_methodology_based_on_zipcode\
_population_density:_http://jedkolko.com/wp-content/uploads/2015/05/full-ZCTA-urban-suburban-rural-\
classification.xlsx_)': "Geography"})

In [6]:
policekillings.columns

Index(['Victims_name', 'Victims_age', 'Victims_gender', 'Victims_race',
       'URL_of_image_of_victim', 'Date_of_Incident_(month/day/year)',
       'Address', 'City', 'State', 'Zip', 'County',
       'Agency_responsible_for_death', 'Cause_of_death',
       'A_brief_description_of_the_circumstances_surrounding_the_death',
       'Official_disposition_of_death_(justified_or_other)',
       'Criminal_Charges?',
       'Link_to_news_article_or_photo_of_official_document',
       'Symptoms_of_mental_illness?', 'Unarmed',
       'Alleged_Weapon_(Source:_WaPo)', 'Alleged_Threat_Level_(Source:_WaPo)',
       'Fleeing_(Source:_WaPo)', 'Body_Camera_(Source:_WaPo)',
       'WaPo_ID_(If_included_in_WaPo_database)', 'Off-Duty_Killing?',
       'Geography', 'ID'],
      dtype='object')

In [7]:
policekillings.dropna(axis = "rows",how="all",inplace=True)

In [8]:
policekillings

,Victims_name,Victims_age,Victims_gender,Victims_race,URL_of_image_of_victim,Date_of_Incident_(month/day/year),Address,City,State,Zip,...,Symptoms_of_mental_illness?,Unarmed,Alleged_Weapon_(Source:_WaPo),Alleged_Threat_Level_(Source:_WaPo),Fleeing_(Source:_WaPo),Body_Camera_(Source:_WaPo),WaPo_ID_(If_included_in_WaPo_database),Off-Duty_Killing?,Geography,ID
0,Eric M. Tellez,28,Male,White,https://fatalencounters.org/wp-content/uploads...,31/12/2019,Broad St.,Globe,AZ,85501.0,...,No,Allegedly Armed,knife,other,not fleeing,no,5332.0,NaN,Rural,7664.0
1,Name withheld by police,NaN,Male,Unknown race,NaN,31/12/2019,7239-7411 I-40,Memphis,AR,38103.0,...,No,Unclear,unclear,other,NaN,NaN,NaN,NaN,Urban,7665.0
2,Terry Hudson,57,Male,Black,NaN,31/12/2019,3600 N 24th St,Omaha,NE,68110.0,...,No,Allegedly Armed,gun,attack,not fleeing,no,5359.0,NaN,Urban,7661.0
3,Malik Williams,23,Male,Black,NaN,31/12/2019,30800 14th Avenue South,Federal Way,WA,98003.0,...,No,Allegedly Armed,gun,attack,not fleeing,no,5358.0,NaN,Suburban,7662.0
4,Frederick Perkins,37,Male,Black,NaN,31/12/2019,17057 N Outer 40 Rd,Chesterfield,MO,63005.0,...,No,Vehicle,vehicle,attack,car,no,5333.0,NaN,Suburban,7667.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7658,Mark Chavez,49,Male,Hispanic,http://www.tricitytribuneusa.com/wp-content/up...,01/01/2013,912 Loma Linda Ave.,Farmington,NM,87401.0,...,No,Allegedly Armed,blunt weapon,NaN,NaN,NaN,NaN,NaN,Urban,1.0
7659,Tyree Bell,31,Male,Black,http://content.omaha.com/media/maps/ps/2013/ja...,01/01/2013,3727 N. 42nd St.,Omaha,NE,68111.0,...,Yes,Allegedly Armed,gun,NaN,NaN,NaN,NaN,NaN,Urban,2.0
7660,Christopher Tavares,21,Male,Hispanic,http://www.krdo.com/image/view/-/17980228/medR...,01/01/2013,Highway 50 and North Elizabeth Street,Pueblo,CO,81008.0,...,No,Allegedly Armed,gun,NaN,NaN,NaN,NaN,NaN,Suburban,4.0
7661,Andrew L. Closson,21,Male,White,http://www.superiortelegram.com/sites/default/...,01/01/2013,U.S. Highway 53,Gordon,WI,54838.0,...,Drug or alcohol use,Allegedly Armed,gun,NaN,NaN,NaN,NaN,NaN,Rural,5.0
7662,Andrew Layton,26,Male,White,http://bloximages.chicago2.vip.townnews.com/ma...,01/01/2013,410 S Riverfront Drive,Mankato,MN,56001.0,...,No,Unarmed,unarmed,NaN,NaN,NaN,NaN,NaN,Suburban,6.0

In [9]:
# killingsaddress = policekillings.loc[:,['Victims_name','Address', 'City', 'State', 'Zip']]
# killingsaddress = killingsaddress.dropna(axis=0, how='any')
# killingsaddress.Zip = killingsaddress.Zip.astype('int64')
# killingsaddress.to_csv('KA.csv')

In [11]:
ka_geocode = pd.read_csv('KA_geocode.csv')
ka_geocode

,index,Victims_name,Address,City,State,Zip,Latitude,Longitude,Accuracy Score,Accuracy Type,Number,Street,Unit Type,Unit Number,City.1,State.1,County,Zip.1,Country,Source
0,0,Eric M. Tellez,Broad St.,Globe,AZ,85501,33.395049,-110.786764,0.9,street_center,NaN,S Broad St,NaN,NaN,Globe,AZ,Gila County,85501.0,US,TIGER/Line® dataset from the US Census Bureau
1,1,Name withheld by police,7239-7411 I-40,Memphis,AR,38103,35.168816,-89.902405,0.6,street_center,NaN,I-40,NaN,NaN,Memphis,TN,Shelby County,38103.0,US,TIGER/Line® dataset from the US Census Bureau
2,2,Terry Hudson,3600 N 24th St,Omaha,NE,68110,41.292023,-95.947237,0.9,rooftop,3600,N 24th St,NaN,NaN,Omaha,NE,Douglas County,68111.0,US,Douglas
3,3,Malik Williams,30800 14th Avenue South,Federal Way,WA,98003,47.325463,-122.316013,1.0,range_interpolation,30800,14th Ave S,NaN,NaN,Federal Way,WA,King County,98003.0,US,TIGER/Line® dataset from the US Census Bureau
4,4,Frederick Perkins,17057 N Outer 40 Rd,Chesterfield,MO,63005,38.671482,-90.588302,1.0,rooftop,17057,N Outer 40th Rd,NaN,NaN,Chesterfield,MO,St. Louis County,63005.0,US,St Louis
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7556,7658,Mark Chavez,912 Loma Linda Ave.,Farmington,NM,87401,36.739514,-108.201029,1.0,rooftop,912,Loma Linda Ave,NaN,NaN,Farmington,NM,San Juan County,87401.0,US,City of Farmington
7557,7659,Tyree Bell,3727 N. 42nd St.,Omaha,NE,68111,41.293110,-95.975491,1.0,rooftop,3727,N 42nd St,NaN,NaN,Omaha,NE,Douglas County,68111.0,US,Douglas
7558,7660,Christopher Tavares,Highway 50 and North Elizabeth Street,Pueblo,CO,81008,38.307617,-104.616047,0.8,intersection,NaN,N Elizabeth St,NaN,NaN,Pueblo,CO,Pueblo County,81008.0,US,TIGER/Line® dataset from the US Census Bureau
7559,7661,Andrew L. Closson,U.S. Highway 53,Gordon,WI,54838,46.245874,-91.801104,1.0,street_center,NaN,US Hwy 53,NaN,NaN,Gordon,WI,Douglas County,54838.0,US,TIGER/Line® dataset from the US Census Bureau
7560,7662,Andrew Layton,410 S Riverfront Drive,Mankato,MN,56001,44.165278,-94.006972,1.0,range_interpolation,410,S Riverfront Dr,NaN,NaN,Mankato,MN,Blue Earth County,56001.0,US,TIGER/Line® dataset from the US Census Bureau

In [112]:
PK_geocode = pd.merge(policekillings, ka_geocode, on='Victims_name')

In [113]:
PK_geocode['Symptoms_of_mental_illness?'].replace({"Unkown": "Unknown", "unknown": "Unknown","Unknown ": "Unknown"}, inplace=True)
PK_geocode['Symptoms_of_mental_illness?'].value_counts()

No                     36297
Yes                     6193
Unknown                 5055
Drug or alcohol use      888
Name: Symptoms_of_mental_illness?, dtype: int64

In [114]:
PK_geocode['Victims_race'].replace({"Unknown race": "Unknown Race"}, inplace=True)
PK_geocode['Victims_race'].value_counts()

Unknown Race        28716
Hispanic             7844
Black                5894
White                5726
Native American       692
Asian                 117
Pacific Islander       42
Name: Victims_race, dtype: int64

In [115]:
PK_geocode = PK_geocode[PK_geocode.columns.drop(list(PK_geocode.filter(regex='_y')))]
PK_geocode.columns = PK_geocode.columns.str.replace("_x",'')
PK_geocode.columns = [x.replace("_(Source:_WaPo)","") for x in PK_geocode.columns]
PK_geocode.columns = [x.replace("Date_of_Incident_(month/day/year)","Date") for x in PK_geocode.columns]

In [116]:
PK_geocode['Body_Camera'] = PK_geocode['Body_Camera'].str.replace('no','No')\
.str.replace('Bystander Video','No').str.replace('Surveillance Video','No')

In [117]:
PK_geocode.dropna(subset = ['Symptoms_of_mental_illness?'],inplace=True)
PK_geocode.dropna(subset = ['Body_Camera'],inplace=True)

In [118]:
PK_geocode.columns

Index(['Victims_name', 'Victims_age', 'Victims_gender', 'Victims_race',
       'URL_of_image_of_victim', 'Date', 'Address', 'City', 'State', 'Zip',
       'County', 'Agency_responsible_for_death', 'Cause_of_death',
       'A_brief_description_of_the_circumstances_surrounding_the_death',
       'Official_disposition_of_death_(justified_or_other)',
       'Criminal_Charges?',
       'Link_to_news_article_or_photo_of_official_document',
       'Symptoms_of_mental_illness?', 'Unarmed', 'Alleged_Weapon',
       'Alleged_Threat_Level', 'Fleeing', 'Body_Camera',
       'WaPo_ID_(If_included_in_WaPo_database)', 'Off-Duty_Killing?',
       'Geography', 'ID', 'index', 'Latitude', 'Longitude', 'Accuracy Score',
       'Accuracy Type', 'Number', 'Street', 'Unit Type', 'Unit Number',
       'City.1', 'State.1', 'Zip.1', 'Country', 'Source'],
      dtype='object')

In [119]:
PK_geocode['Symptoms_of_mental_illness?'].value_counts()

No                     20332
Yes                     4423
Unknown                 1971
Drug or alcohol use      518
Name: Symptoms_of_mental_illness?, dtype: int64

In [120]:
PK_geocode.columns

Index(['Victims_name', 'Victims_age', 'Victims_gender', 'Victims_race',
       'URL_of_image_of_victim', 'Date', 'Address', 'City', 'State', 'Zip',
       'County', 'Agency_responsible_for_death', 'Cause_of_death',
       'A_brief_description_of_the_circumstances_surrounding_the_death',
       'Official_disposition_of_death_(justified_or_other)',
       'Criminal_Charges?',
       'Link_to_news_article_or_photo_of_official_document',
       'Symptoms_of_mental_illness?', 'Unarmed', 'Alleged_Weapon',
       'Alleged_Threat_Level', 'Fleeing', 'Body_Camera',
       'WaPo_ID_(If_included_in_WaPo_database)', 'Off-Duty_Killing?',
       'Geography', 'ID', 'index', 'Latitude', 'Longitude', 'Accuracy Score',
       'Accuracy Type', 'Number', 'Street', 'Unit Type', 'Unit Number',
       'City.1', 'State.1', 'Zip.1', 'Country', 'Source'],
      dtype='object')

In [121]:
PK_geocode.drop_duplicates(inplace=True)

In [122]:
# PK_geocode[PK_geocode['Date'].str.contains("2014")]
PK_geocode['Date'] = PK_geocode['Date'].str.replace('2014','2015')

In [55]:
PK_geocode.to_csv('PK_geocode.csv')

In [145]:
census = pd.read_csv('censusdata/acs2017_county_data.csv')

In [146]:
census = census[census.State != 'Puerto Rico']

In [147]:
census.columns

Index(['CountyId', 'State', 'County', 'TotalPop', 'Men', 'Women', 'Hispanic',
       'White', 'Black', 'Native', 'Asian', 'Pacific', 'VotingAgeCitizen',
       'Income', 'IncomeErr', 'IncomePerCap', 'IncomePerCapErr', 'Poverty',
       'ChildPoverty', 'Professional', 'Service', 'Office', 'Construction',
       'Production', 'Drive', 'Carpool', 'Transit', 'Walk', 'OtherTransp',
       'WorkAtHome', 'MeanCommute', 'Employed', 'PrivateWork', 'PublicWork',
       'SelfEmployed', 'FamilyWork', 'Unemployment'],
      dtype='object')

In [148]:
census['Unemployment_per_state'] = census.groupby('State')['Unemployment'].transform('mean')
census['Total_Population'] = census.groupby('State')['TotalPop'].transform('sum')

list_of_races = ['Hispanic','White', 'Black', 'Native', 'Asian', 'Pacific']
for race in list_of_races:
    census['{}_percentage'.format(race)] = census.groupby('State')[race].transform('mean')
    census['{}_percentage'.format(race)] = census['{}_percentage'.format(race)].round(2)

In [149]:
census = census[['State','Unemployment_per_state',
       'Total_Population', 'Hispanic_percentage', 'White_percentage',
       'Black_percentage', 'Native_percentage', 'Asian_percentage',
       'Pacific_percentage']]

In [150]:
census.drop_duplicates(inplace=True)

In [151]:
census

,State,Unemployment_per_state,Total_Population,Hispanic_percentage,White_percentage,Black_percentage,Native_percentage,Asian_percentage,Pacific_percentage
0,Alabama,9.023881,4850771,3.30,65.17,28.67,0.61,0.71,0.02
67,Alaska,9.655172,738565,5.09,48.42,1.18,31.63,5.98,0.54
96,Arizona,9.766667,6809946,30.89,50.83,1.81,13.23,1.29,0.13
111,Arkansas,7.292000,2977944,5.09,75.63,16.13,0.54,0.69,0.08
186,California,8.265517,38982847,30.07,54.76,2.94,1.65,7.07,0.29
244,Colorado,5.793750,5436519,20.04,74.66,1.48,0.83,1.11,0.11
308,Connecticut,6.775000,3594478,11.42,76.04,6.48,0.12,3.58,0.00
316,Delaware,6.433333,943732,8.53,65.37,20.10,0.40,2.87,0.00
319,District of Columbia,8.000000,672391,10.70,36.00,46.90,0.20,3.70,0.00
320,Florida,7.765672,20278447,13.73,68.12,14.20,0.40,1.54,0.08
387,Georgia,8.053459,10201635,6.23,62.56,28.14,0.19,1.20,0.05
546,Hawaii,4.120000,1421658,9.72,26.00,0.80,0.14,30.76,14.46
551,Idaho,5.622727,1657375,12.71,82.92,0.38,1.52,0.65,0.09
595,Illinois,6.611765,12854526,4.82,87.05,5.15,0.15,1.22,0.02
697,Indiana,5.445652,6614418,3.88,90.75,2.66,0.19,1.01,0.02
789,Iowa,3.895960,3118102,4.54,91.39,1.38,0.29,1.08,0.06
888,Kansas,3.990476,2903820,9.75,84.74,1.75,0.78,0.80,0.05
993,Kentucky,7.672500,4424376,2.30,91.81,3.65,0.18,0.51,0.03
1113,Louisiana,7.871875,4663461,3.49,61.73,31.78,0.62,0.81,0.02
1177,Maine,5.800000,1330158,1.41,94.39,0.78,0.77,0.78,0.01
1193,Maryland,6.120833,5996079,5.83,68.12,19.84,0.19,3.30,0.02
1217,Massachusetts,5.842857,6789319,8.99,77.83,5.70,0.29,4.03,0.02
1231,Michigan,7.620482,9925568,3.46,88.10,3.87,1.26,1.00,0.02
1314,Minnesota,3.954023,5490726,4.28,88.94,1.63,1.94,1.44,0.03
1401,Mississippi,10.007317,2986220,2.40,54.32,41.35,0.51,0.51,0.02
1483,Missouri,6.026087,6075300,2.80,90.57,3.56,0.50,0.63,0.08
1598,Montana,4.525000,1029862,2.90,86.57,0.22,7.77,0.47,0.03
1654,Nebraska,2.847312,1893921,6.54,89.51,0.82,1.19,0.51,0.07
1747,Nevada,7.394118,2887725,17.32,72.29,2.19,3.86,2.03,0.22
1764,New Hampshire,4.540000,1331848,2.32,92.95,1.02,0.19,1.82,0.02
1774,New Jersey,7.119048,8960161,16.94,62.44,11.34,0.10,7.10,0.00
1795,New Mexico,7.566667,2084828,47.38,41.98,1.25,6.88,0.76,0.02
1828,New York,6.577419,19798228,7.65,81.32,5.81,0.37,2.83,0.02
1890,North Carolina,7.965000,10052564,7.09,68.11,20.16,1.55,1.14,0.04
1990,North Dakota,2.728302,745475,2.78,87.61,0.88,6.58,0.49,0.02
2043,Ohio,6.084091,11609756,2.62,90.29,4.08,0.15,0.93,0.02
2131,Oklahoma,5.853247,3896251,8.83,70.91,3.38,8.90,0.76,0.11
2208,Oregon,7.455556,4025127,11.73,80.93,0.74,1.72,1.60,0.27
2244,Pennsylvania,6.031343,12790505,4.19,88.25,4.51,0.12,1.44,0.00
2311,Rhode Island,5.860000,1056138,7.46,84.34,3.00,0.32,2.50,0.06
2316,South Carolina,8.773913,4893444,4.50,57.00,35.49,0.35,0.80,0.05
2362,South Dakota,4.821212,855444,2.57,80.18,0.56,13.89,0.72,0.06
2428,Tennessee,7.344211,6597381,3.39,86.43,7.25,0.26,0.68,0.04
2523,Texas,6.028346,27419612,34.52,56.56,6.15,0.33,0.98,0.07
2777,Utah,4.365517,2993941,8.94,85.34,0.43,2.74,0.79,0.31
2806,Vermont,4.528571,624636,1.68,94.25,0.84,0.35,0.91,0.02
2820,Virginia,6.033835,8365952,5.13,71.68,18.40,0.26,2.06,0.03
2953,Washington,6.702564,7169967,14.00,76.38,1.24,2.02,2.67,0.29
2992,West Virginia,8.063636,1836843,1.22,94.43,2.30,0.18,0.44,0.02
3047,Wisconsin,4.570833,5763217,3.66,89.28,1.59,2.67,1.21,0.02
3119,Wyoming,4.282609,583200,8.17,86.77,0.58,1.77,0.75,0.04

In [105]:
# PK_geocode = pd.merge(PK_geocode, census, on='State')

In [154]:
transfer = pd.read_csv('50_us_states_all_data.csv')
transfer.rename(columns={"Title": "State"},inplace=True)

In [155]:
transfer

          ALL_CAPS           State TwoLetters Shortcut
0          ALABAMA         Alabama         AL     Ala.
1           ALASKA          Alaska         AK   Alaska
2          ARIZONA         Arizona         AZ    Ariz.
3         ARKANSAS        Arkansas         AR     Ark.
4       CALIFORNIA      California         CA   Calif.
5         COLORADO        Colorado         CO    Colo.
6      CONNECTICUT     Connecticut         CT    Conn.
7         DELAWARE        Delaware         DE     Del.
8          FLORIDA         Florida         FL     Fla.
9          GEORGIA         Georgia         GA      Ga.
10          HAWAII          Hawaii         HI   Hawaii
11           IDAHO           Idaho         ID    Idaho
12        ILLINOIS        Illinois         IL     Ill.
13         INDIANA         Indiana         IN     Ind.
14            IOWA            Iowa         IA     Iowa
15          KANSAS          Kansas         KS     Kan.
16        KENTUCKY        Kentucky         KY      Ky.
17       LOUISIANA       Louisiana         LA      La.
18           MAINE           Maine         ME    Maine
19        MARYLAND        Maryland         MD      Md.
20   MASSACHUSETTS   Massachusetts         MA    Mass.
21        MICHIGAN        Michigan         MI    Mich.
22       MINNESOTA       Minnesota         MN    Minn.
23     MISSISSIPPI     Mississippi         MS    Miss.
24        MISSOURI        Missouri         MO      Mo.
25         MONTANA         Montana         MT    Mont.
26        NEBRASKA        Nebraska         NE     Neb.
27          NEVADA          Nevada         NV     Nev.
28   NEW HAMPSHIRE   New Hampshire         NH     N.H.
29      NEW JERSEY      New Jersey         NJ     N.J.
30      NEW MEXICO      New Mexico         NM     N.M.
31        NEW YORK        New York         NY     N.Y.
32  NORTH CAROLINA  North Carolina         NC     N.C.
33    NORTH DAKOTA    North Dakota         ND     N.D.
34            OHIO            Ohio         OH     Ohio
35        OKLAHOMA        Oklahoma         OK    Okla.
36          OREGON          Oregon         OR     Ore.
37    PENNSYLVANIA    Pennsylvania         PA      Pa.
38    RHODE ISLAND    Rhode Island         RI     R.I.
39  SOUTH CAROLINA  South Carolina         SC     S.C.
40    SOUTH DAKOTA    South Dakota         SD     S.D.
41       TENNESSEE       Tennessee         TN    Tenn.
42           TEXAS           Texas         TX    Texas
43            UTAH            Utah         UT     Utah
44         VERMONT         Vermont         VT      Vt.
45        VIRGINIA        Virginia         VA      Va.
46      WASHINGTON      Washington         WA    Wash.
47   WEST VIRGINIA   West Virginia         WV    W.Va.
48       WISCONSIN       Wisconsin         WI     Wis.
49         WYOMING         Wyoming         WY     Wyo.

In [156]:
census = pd.merge(census,transfer, on = 'State')
# transfer

In [159]:
census.rename(columns={"State": "Title",'TwoLetters':'State'},inplace=True)

In [161]:
temp = pd.merge(census,PK_geocode, on='State')

In [163]:
temp.columns

Index(['Title', 'Unemployment_per_state', 'Total_Population',
       'Hispanic_percentage', 'White_percentage', 'Black_percentage',
       'Native_percentage', 'Asian_percentage', 'Pacific_percentage',
       'ALL_CAPS', 'State', 'Shortcut', 'Victims_name', 'Victims_age',
       'Victims_gender', 'Victims_race', 'URL_of_image_of_victim', 'Date',
       'Address', 'City', 'Zip', 'County', 'Agency_responsible_for_death',
       'Cause_of_death',
       'A_brief_description_of_the_circumstances_surrounding_the_death',
       'Official_disposition_of_death_(justified_or_other)',
       'Criminal_Charges?',
       'Link_to_news_article_or_photo_of_official_document',
       'Symptoms_of_mental_illness?', 'Unarmed', 'Alleged_Weapon',
       'Alleged_Threat_Level', 'Fleeing', 'Body_Camera',
       'WaPo_ID_(If_included_in_WaPo_database)', 'Off-Duty_Killing?',
       'Geography', 'ID', 'index', 'Latitude', 'Longitude', 'Accuracy Score',
       'Accuracy Type', 'Number', 'Street', 'Unit Type', 'Unit Number',
       'City.1', 'State.1', 'Zip.1', 'Country', 'Source'],
      dtype='object')

In [164]:
temp.to_csv('PK_geocode.csv')

In [165]:
temp

,Title,Unemployment_per_state,Total_Population,Hispanic_percentage,White_percentage,Black_percentage,Native_percentage,Asian_percentage,Pacific_percentage,ALL_CAPS,...,Accuracy Type,Number,Street,Unit Type,Unit Number,City.1,State.1,Zip.1,Country,Source
0,Alabama,9.023881,4850771,3.30,65.17,28.67,0.61,0.71,0.02,ALABAMA,...,street_center,NaN,I-40,NaN,NaN,Memphis,TN,38103.0,US,TIGER/Line® dataset from the US Census Bureau
1,Alabama,9.023881,4850771,3.30,65.17,28.67,0.61,0.71,0.02,ALABAMA,...,rooftop,7111,Martin Luther King Jr Blvd,NaN,NaN,Houston,TX,77033.0,US,City of Houston
2,Alabama,9.023881,4850771,3.30,65.17,28.67,0.61,0.71,0.02,ALABAMA,...,rooftop,3015,Old State Rd 25,NaN,NaN,Lafayette,IN,47905.0,US,Tippecanoe
3,Alabama,9.023881,4850771,3.30,65.17,28.67,0.61,0.71,0.02,ALABAMA,...,rooftop,2174,Pine St,NaN,NaN,Redding,CA,96001.0,US,Shasta County
4,Alabama,9.023881,4850771,3.30,65.17,28.67,0.61,0.71,0.02,ALABAMA,...,range_interpolation,3600,W 4th St,NaN,NaN,Los Angeles,CA,90020.0,US,TIGER/Line® dataset from the US Census Bureau
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27226,Wyoming,4.282609,583200,8.17,86.77,0.58,1.77,0.75,0.04,WYOMING,...,street_center,NaN,Wyoming Ave,NaN,NaN,Laramie,WY,82070.0,US,TIGER/Line® dataset from the US Census Bureau
27227,Wyoming,4.282609,583200,8.17,86.77,0.58,1.77,0.75,0.04,WYOMING,...,street_center,NaN,Anderson Dairy Rd,NaN,NaN,Douglas,WY,82633.0,US,TIGER/Line® dataset from the US Census Bureau
27228,Wyoming,4.282609,583200,8.17,86.77,0.58,1.77,0.75,0.04,WYOMING,...,rooftop,200,Stinson Ave,NaN,NaN,Cheyenne,WY,82007.0,US,Laramie
27229,Wyoming,4.282609,583200,8.17,86.77,0.58,1.77,0.75,0.04,WYOMING,...,rooftop,1654,Kit Carson Ave,NaN,NaN,Casper,WY,82604.0,US,Natrona
27230,Wyoming,4.282609,583200,8.17,86.77,0.58,1.77,0.75,0.04,WYOMING,...,intersection,NaN,N Garner Lake Rd,NaN,NaN,Gillette,WY,82716.0,US,TIGER/Line® dataset from the US Census Bureau