In [56]:
import pandas as pd

In [3]:
policekillings = pd.read_csv('data/police_killings.csv')

In [4]:
policekillings.columns = policekillings.columns.str.replace("'",'').str.replace(' ','_')
policekillings.columns = policekillings.columns.str.replace('Street_Address_of_Incident','Address').str.replace('Zipcode','Zip')
policekillings = policekillings[policekillings.columns.drop(list(policekillings.filter(regex='Unnamed')))]

In [5]:
policekillings = policekillings.rename(columns={'Geography_(via_Trulia_methodology_based_on_zipcode\
_population_density:_http://jedkolko.com/wp-content/uploads/2015/05/full-ZCTA-urban-suburban-rural-\
classification.xlsx_)': "Geography"})

In [6]:
policekillings.columns

Index(['Victims_name', 'Victims_age', 'Victims_gender', 'Victims_race',
       'URL_of_image_of_victim', 'Date_of_Incident_(month/day/year)',
       'Address', 'City', 'State', 'Zip', 'County',
       'Agency_responsible_for_death', 'Cause_of_death',
       'A_brief_description_of_the_circumstances_surrounding_the_death',
       'Official_disposition_of_death_(justified_or_other)',
       'Criminal_Charges?',
       'Link_to_news_article_or_photo_of_official_document',
       'Symptoms_of_mental_illness?', 'Unarmed',
       'Alleged_Weapon_(Source:_WaPo)', 'Alleged_Threat_Level_(Source:_WaPo)',
       'Fleeing_(Source:_WaPo)', 'Body_Camera_(Source:_WaPo)',
       'WaPo_ID_(If_included_in_WaPo_database)', 'Off-Duty_Killing?',
       'Geography', 'ID'],
      dtype='object')

In [7]:
policekillings.dropna(axis = "rows",how="all",inplace=True)

In [8]:
policekillings

,Victims_name,Victims_age,Victims_gender,Victims_race,URL_of_image_of_victim,Date_of_Incident_(month/day/year),Address,City,State,Zip,...,Symptoms_of_mental_illness?,Unarmed,Alleged_Weapon_(Source:_WaPo),Alleged_Threat_Level_(Source:_WaPo),Fleeing_(Source:_WaPo),Body_Camera_(Source:_WaPo),WaPo_ID_(If_included_in_WaPo_database),Off-Duty_Killing?,Geography,ID
0,Eric M. Tellez,28,Male,White,https://fatalencounters.org/wp-content/uploads...,31/12/2019,Broad St.,Globe,AZ,85501.0,...,No,Allegedly Armed,knife,other,not fleeing,no,5332.0,NaN,Rural,7664.0
1,Name withheld by police,NaN,Male,Unknown race,NaN,31/12/2019,7239-7411 I-40,Memphis,AR,38103.0,...,No,Unclear,unclear,other,NaN,NaN,NaN,NaN,Urban,7665.0
2,Terry Hudson,57,Male,Black,NaN,31/12/2019,3600 N 24th St,Omaha,NE,68110.0,...,No,Allegedly Armed,gun,attack,not fleeing,no,5359.0,NaN,Urban,7661.0
3,Malik Williams,23,Male,Black,NaN,31/12/2019,30800 14th Avenue South,Federal Way,WA,98003.0,...,No,Allegedly Armed,gun,attack,not fleeing,no,5358.0,NaN,Suburban,7662.0
4,Frederick Perkins,37,Male,Black,NaN,31/12/2019,17057 N Outer 40 Rd,Chesterfield,MO,63005.0,...,No,Vehicle,vehicle,attack,car,no,5333.0,NaN,Suburban,7667.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7658,Mark Chavez,49,Male,Hispanic,http://www.tricitytribuneusa.com/wp-content/up...,01/01/2013,912 Loma Linda Ave.,Farmington,NM,87401.0,...,No,Allegedly Armed,blunt weapon,NaN,NaN,NaN,NaN,NaN,Urban,1.0
7659,Tyree Bell,31,Male,Black,http://content.omaha.com/media/maps/ps/2013/ja...,01/01/2013,3727 N. 42nd St.,Omaha,NE,68111.0,...,Yes,Allegedly Armed,gun,NaN,NaN,NaN,NaN,NaN,Urban,2.0
7660,Christopher Tavares,21,Male,Hispanic,http://www.krdo.com/image/view/-/17980228/medR...,01/01/2013,Highway 50 and North Elizabeth Street,Pueblo,CO,81008.0,...,No,Allegedly Armed,gun,NaN,NaN,NaN,NaN,NaN,Suburban,4.0
7661,Andrew L. Closson,21,Male,White,http://www.superiortelegram.com/sites/default/...,01/01/2013,U.S. Highway 53,Gordon,WI,54838.0,...,Drug or alcohol use,Allegedly Armed,gun,NaN,NaN,NaN,NaN,NaN,Rural,5.0
7662,Andrew Layton,26,Male,White,http://bloximages.chicago2.vip.townnews.com/ma...,01/01/2013,410 S Riverfront Drive,Mankato,MN,56001.0,...,No,Unarmed,unarmed,NaN,NaN,NaN,NaN,NaN,Suburban,6.0

In [9]:
# killingsaddress = policekillings.loc[:,['Victims_name','Address', 'City', 'State', 'Zip']]
# killingsaddress = killingsaddress.dropna(axis=0, how='any')
# killingsaddress.Zip = killingsaddress.Zip.astype('int64')
# killingsaddress.to_csv('KA.csv')

In [11]:
ka_geocode = pd.read_csv('KA_geocode.csv')
ka_geocode

,index,Victims_name,Address,City,State,Zip,Latitude,Longitude,Accuracy Score,Accuracy Type,Number,Street,Unit Type,Unit Number,City.1,State.1,County,Zip.1,Country,Source
0,0,Eric M. Tellez,Broad St.,Globe,AZ,85501,33.395049,-110.786764,0.9,street_center,NaN,S Broad St,NaN,NaN,Globe,AZ,Gila County,85501.0,US,TIGER/Line® dataset from the US Census Bureau
1,1,Name withheld by police,7239-7411 I-40,Memphis,AR,38103,35.168816,-89.902405,0.6,street_center,NaN,I-40,NaN,NaN,Memphis,TN,Shelby County,38103.0,US,TIGER/Line® dataset from the US Census Bureau
2,2,Terry Hudson,3600 N 24th St,Omaha,NE,68110,41.292023,-95.947237,0.9,rooftop,3600,N 24th St,NaN,NaN,Omaha,NE,Douglas County,68111.0,US,Douglas
3,3,Malik Williams,30800 14th Avenue South,Federal Way,WA,98003,47.325463,-122.316013,1.0,range_interpolation,30800,14th Ave S,NaN,NaN,Federal Way,WA,King County,98003.0,US,TIGER/Line® dataset from the US Census Bureau
4,4,Frederick Perkins,17057 N Outer 40 Rd,Chesterfield,MO,63005,38.671482,-90.588302,1.0,rooftop,17057,N Outer 40th Rd,NaN,NaN,Chesterfield,MO,St. Louis County,63005.0,US,St Louis
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7556,7658,Mark Chavez,912 Loma Linda Ave.,Farmington,NM,87401,36.739514,-108.201029,1.0,rooftop,912,Loma Linda Ave,NaN,NaN,Farmington,NM,San Juan County,87401.0,US,City of Farmington
7557,7659,Tyree Bell,3727 N. 42nd St.,Omaha,NE,68111,41.293110,-95.975491,1.0,rooftop,3727,N 42nd St,NaN,NaN,Omaha,NE,Douglas County,68111.0,US,Douglas
7558,7660,Christopher Tavares,Highway 50 and North Elizabeth Street,Pueblo,CO,81008,38.307617,-104.616047,0.8,intersection,NaN,N Elizabeth St,NaN,NaN,Pueblo,CO,Pueblo County,81008.0,US,TIGER/Line® dataset from the US Census Bureau
7559,7661,Andrew L. Closson,U.S. Highway 53,Gordon,WI,54838,46.245874,-91.801104,1.0,street_center,NaN,US Hwy 53,NaN,NaN,Gordon,WI,Douglas County,54838.0,US,TIGER/Line® dataset from the US Census Bureau
7560,7662,Andrew Layton,410 S Riverfront Drive,Mankato,MN,56001,44.165278,-94.006972,1.0,range_interpolation,410,S Riverfront Dr,NaN,NaN,Mankato,MN,Blue Earth County,56001.0,US,TIGER/Line® dataset from the US Census Bureau

In [42]:
PK_geocode = pd.merge(policekillings, ka_geocode, on='Victims_name')

In [43]:
PK_geocode['Symptoms_of_mental_illness?'].replace({"Unkown": "Unknown", "unknown": "Unknown","Unknown ": "Unknown"}, inplace=True)
PK_geocode['Symptoms_of_mental_illness?'].value_counts()

No                     36297
Yes                     6193
Unknown                 5055
Drug or alcohol use      888
Name: Symptoms_of_mental_illness?, dtype: int64

In [44]:
PK_geocode['Victims_race'].replace({"Unknown race": "Unknown Race"}, inplace=True)
PK_geocode['Victims_race'].value_counts()

Unknown Race        28716
Hispanic             7844
Black                5894
White                5726
Native American       692
Asian                 117
Pacific Islander       42
Name: Victims_race, dtype: int64

In [45]:
PK_geocode = PK_geocode[PK_geocode.columns.drop(list(PK_geocode.filter(regex='_y')))]
PK_geocode.columns = PK_geocode.columns.str.replace("_x",'')
PK_geocode.columns = [x.replace("_(Source:_WaPo)","") for x in PK_geocode.columns]
PK_geocode.columns = [x.replace("Date_of_Incident_(month/day/year)","Date") for x in PK_geocode.columns]

In [46]:
PK_geocode['Body_Camera'] = PK_geocode['Body_Camera'].str.replace('no','No')\
.str.replace('Bystander Video','No').str.replace('Surveillance Video','No')

In [47]:
PK_geocode.dropna(subset = ['Symptoms_of_mental_illness?'],inplace=True)
PK_geocode.dropna(subset = ['Body_Camera'],inplace=True)

In [48]:
PK_geocode.shape

(27244, 41)

In [49]:
PK_geocode['Symptoms_of_mental_illness?'].value_counts()

No                     20332
Yes                     4423
Unknown                 1971
Drug or alcohol use      518
Name: Symptoms_of_mental_illness?, dtype: int64

In [50]:
PK_geocode.columns

Index(['Victims_name', 'Victims_age', 'Victims_gender', 'Victims_race',
       'URL_of_image_of_victim', 'Date', 'Address', 'City', 'State', 'Zip',
       'County', 'Agency_responsible_for_death', 'Cause_of_death',
       'A_brief_description_of_the_circumstances_surrounding_the_death',
       'Official_disposition_of_death_(justified_or_other)',
       'Criminal_Charges?',
       'Link_to_news_article_or_photo_of_official_document',
       'Symptoms_of_mental_illness?', 'Unarmed', 'Alleged_Weapon',
       'Alleged_Threat_Level', 'Fleeing', 'Body_Camera',
       'WaPo_ID_(If_included_in_WaPo_database)', 'Off-Duty_Killing?',
       'Geography', 'ID', 'index', 'Latitude', 'Longitude', 'Accuracy Score',
       'Accuracy Type', 'Number', 'Street', 'Unit Type', 'Unit Number',
       'City.1', 'State.1', 'Zip.1', 'Country', 'Source'],
      dtype='object')

In [51]:
PK_geocode.drop_duplicates(inplace=True)

In [54]:
# PK_geocode[PK_geocode['Date'].str.contains("2014")]
PK_geocode['Date'] = PK_geocode['Date'].str.replace('2014','2015')

In [55]:
PK_geocode.to_csv('PK_geocode.csv')

In [96]:
census = pd.read_csv('censusdata/acs2017_county_data.csv')

In [97]:
census = census[census.State != 'Puerto Rico']

In [100]:
census.columns

Index(['CountyId', 'State', 'County', 'TotalPop', 'Men', 'Women', 'Hispanic',
       'White', 'Black', 'Native', 'Asian', 'Pacific', 'VotingAgeCitizen',
       'Income', 'IncomeErr', 'IncomePerCap', 'IncomePerCapErr', 'Poverty',
       'ChildPoverty', 'Professional', 'Service', 'Office', 'Construction',
       'Production', 'Drive', 'Carpool', 'Transit', 'Walk', 'OtherTransp',
       'WorkAtHome', 'MeanCommute', 'Employed', 'PrivateWork', 'PublicWork',
       'SelfEmployed', 'FamilyWork', 'Unemployment', 'Unemployment_per_state',
       'Total_Population', 'Hispanic_percentage', 'White_percentage',
       'Black_percentage', 'Native_percentage', 'Asian_percentage',
       'Pacific_percentage'],
      dtype='object')

In [102]:
census['Unemployment_per_state'] = census.groupby('State')['Unemployment'].transform('mean')
census['Total_Population'] = census.groupby('State')['TotalPop'].transform('sum')

list_of_races = ['Hispanic','White', 'Black', 'Native', 'Asian', 'Pacific']
for race in list_of_races:
    census['{}_percentage'.format(race)] = census.groupby('State')[race].transform('mean')
    census['{}_percentage'.format(race)] = census['{}_percentage'.format(race)].round(2)

In [103]:
census

,CountyId,State,County,TotalPop,Men,Women,Hispanic,White,Black,Native,...,FamilyWork,Unemployment,Unemployment_per_state,Total_Population,Hispanic_percentage,White_percentage,Black_percentage,Native_percentage,Asian_percentage,Pacific_percentage
0,1001,Alabama,Autauga County,55036,26899,28137,2.7,75.4,18.9,0.3,...,0.1,5.2,9.023881,4850771,3.30,65.17,28.67,0.61,0.71,0.02
1,1003,Alabama,Baldwin County,203360,99527,103833,4.4,83.1,9.5,0.8,...,0.1,5.5,9.023881,4850771,3.30,65.17,28.67,0.61,0.71,0.02
2,1005,Alabama,Barbour County,26201,13976,12225,4.2,45.7,47.8,0.2,...,0.3,12.4,9.023881,4850771,3.30,65.17,28.67,0.61,0.71,0.02
3,1007,Alabama,Bibb County,22580,12251,10329,2.4,74.6,22.0,0.4,...,0.3,8.2,9.023881,4850771,3.30,65.17,28.67,0.61,0.71,0.02
4,1009,Alabama,Blount County,57667,28490,29177,9.0,87.4,1.5,0.3,...,0.1,4.9,9.023881,4850771,3.30,65.17,28.67,0.61,0.71,0.02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3137,56037,Wyoming,Sweetwater County,44527,22981,21546,16.0,79.6,0.8,0.6,...,0.0,5.2,4.282609,583200,8.17,86.77,0.58,1.77,0.75,0.04
3138,56039,Wyoming,Teton County,22923,12169,10754,15.0,81.5,0.5,0.3,...,0.0,1.3,4.282609,583200,8.17,86.77,0.58,1.77,0.75,0.04
3139,56041,Wyoming,Uinta County,20758,10593,10165,9.1,87.7,0.1,0.9,...,0.4,6.4,4.282609,583200,8.17,86.77,0.58,1.77,0.75,0.04
3140,56043,Wyoming,Washakie County,8253,4118,4135,14.2,82.2,0.3,0.4,...,0.2,6.1,4.282609,583200,8.17,86.77,0.58,1.77,0.75,0.04
3141,56045,Wyoming,Weston County,7117,3756,3361,1.4,91.6,0.5,0.1,...,1.1,2.2,4.282609,583200,8.17,86.77,0.58,1.77,0.75,0.04